<div class="item item1">
            <div class="media-img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" style="width:270px;height:130px;"/></a></div>
            <div class="content">
              <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
              <span class='time'>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
              <div class="desc">[field:description function="cn_substr(@me,200)"/]...</div>
            </div>
          </div>