<?php
$z[0]=Array("pubdate","",123,166);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",179,224);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/m',@me)";
$z[2]=Array("arcurl","",296,311);
$z[2][4]=array();
$z[3]=Array("title","",320,334);
$z[3][4]=array();
$z[4]=Array("title","",336,350);
$z[4][4]=array();
$z[5]=Array("description","",390,439);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,60)";

?>