<?php
$z[0]=Array("pubdate","",124,167);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",180,225);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/m',@me)";
$z[2]=Array("arcurl","",299,314);
$z[2][4]=array();
$z[3]=Array("title","",323,337);
$z[3][4]=array();
$z[4]=Array("title","",339,353);
$z[4][4]=array();
$z[5]=Array("description","",394,443);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,60)";

?>