<?php
$z[0]=Array("arcurl","",153,168);
$z[0][4]=array();
$z[1]=Array("title","",177,191);
$z[1][4]=array();
$z[2]=Array("title","",193,207);
$z[2][4]=array();
$z[3]=Array("description","",252,302);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,200)";
$z[4]=Array("pubdate","",373,420);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("arcurl","",459,474);
$z[5][4]=array();

?>