<li class='wow fadeInUp' data-wow-delay='.1s'>
              <div class="media">
                <div class="media-body">
                  <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                  <p  class="desc">[field:description function="cn_substr(@me,200)"/]...</p>
                  <p class='clearfix'><span class='time right'>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span><a class='left news_more' href='[field:arcurl/]' />[查看更多]</a></p>
                </div>
              </div>
            </li>