<?php
$z[0]=Array("arcurl","",156,171);
$z[0][4]=array();
$z[1]=Array("title","",180,194);
$z[1][4]=array();
$z[2]=Array("title","",196,210);
$z[2][4]=array();
$z[3]=Array("description","",256,306);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,200)";
$z[4]=Array("pubdate","",378,425);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("arcurl","",464,479);
$z[5][4]=array();

?>