<div class='news_list clearfix not-animated'  data-animate="slideInUp" data-delay="400">
          <div class='date'><span>[field:pubdate function="MyDate('d',@me)"/]</span><span>[field:pubdate function="MyDate('Y/m',@me)"/]</span></div>
          <div class='content2'>
            <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
            <div class="desc">[field:description function="cn_substr(@me,60)"/]...</div>
          </div>
        </div>