<?php
$z[0]=Array("pubdate","",673,716);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",729,774);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/m',@me)";
$z[2]=Array("arcurl","",848,863);
$z[2][4]=array();
$z[3]=Array("title","",872,886);
$z[3][4]=array();
$z[4]=Array("title","",888,902);
$z[4][4]=array();
$z[5]=Array("description","",943,992);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,60)";

?>