<img src="../../uploads/allimg/171213/1-1G2131112210-L.jpg">
       </div>
    </div>
  </section>
</div>

<!-- 产品中心end -->   
  
  
  
<!-- 新闻资讯start -->
<section id="home_news">
  <div class="container">
    <div class="home_title wow fadeInUp"  >
      <h2>新闻资讯</h2>
      <p> <span>— 传承千年 中医养生 —</span> </p>
    </div>
    <div class="h_news">
      <div class="col-md-4 col-sm-12 col-xs-12 news_right"> {dede:arclist typeid='4' limit='0,2' titlelen='32' orderby='pubdate'}
        <div class='news_list clearfix not-animated'  data-animate="slideInUp" data-delay="400">
          <div class='date'><span>[field:pubdate function="MyDate('d',@me)"/]</span><span>[field:pubdate function="MyDate('Y/m',@me)"/]</span></div>
          <div class='content2'>
            <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
            <div class="desc">[field:description function="cn_substr(@me,60)"/]...</div>
          </div>
        </div>