<?php
$z[0]=Array("field","",11,37);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",68,96);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",98,127);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n              <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n              ",213,355);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>