<?php
$z[0]=Array("channelartlist","\r\n        <li class=\"wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n          <h3>{dede:field name='typename'/}</h3>\r\n          <ul>\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a class=\"btn-medium btn-medium-main\" href='[field:typeurl/]'><span>[field:typename/]</span></a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",103,526);
$z[0][4]=array();
$z[0][4]['typeid']="1,4,7";
$z[1]=Array("global","",660,682);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",714,738);
$z[2][4]=array();
$z[2][4]['name']="cfg_email";
$z[3]=Array("global","",770,792);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",1108,1134);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1187,1211);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("flink","   [field:link /]   ",1261,1343);
$z[6][4]=array();
$z[6][4]['titlelen']="20";
$z[6][4]['row']="20";
$z[6][4]['type']="text";
$z[7]=Array("global","",1603,1625);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";

?>