<?php
$z[0]=Array("global","",326,352);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",883,910);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",2125,2160);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("arclist","\r\n        <div class='news_list clearfix not-animated'  data-animate=\"slideInUp\" data-delay=\"400\">\r\n          <div class='date'><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span><span>[field:pubdate function=\"MyDate('Y/m',@me)\"/]</span></div>\r\n          <div class='content2'>\r\n            <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n            <div class=\"desc\">[field:description function=\"cn_substr(@me,60)\"/]...</div>\r\n          </div>\r\n        </div>\r\n        ",3592,4182);
$z[3][4]=array();
$z[3][4]['typeid']="4";
$z[3][4]['limit']="0,2";
$z[3][4]['titlelen']="32";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n          <div class=\"item item1\">\r\n            <div class=\"media-img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" style=\"width:270px;height:130px;\"/></a></div>\r\n            <div class=\"content\">\r\n              <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n              <span class='time'>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n              <div class=\"desc\">[field:description function=\"cn_substr(@me,200)\"/]...</div>\r\n            </div>\r\n          </div>\r\n          ",4319,4978);
$z[4][4]=array();
$z[4][4]['typeid']="4";
$z[4][4]['limit']="3,2";
$z[4][4]['titlelen']="32";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("type"," <a href=\"[field:typelink/]\"><span>查看更多</span></a>",6964,7056);
$z[5][4]=array();
$z[5][4]['typeid']="2";
$z[6]=Array("include","",7164,7201);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>