<?php
$z[0]=Array("arclist","\r\n\r\n[field:pubdate function=strftime('%Y-%m-%d',@me)/]\r\n\r\n",165,286);
$z[0][4]=array();
$z[0][4]['row']="1";
$z[0][4]['titlelen']="24";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("channel","\r\n\r\n<url>\r\n\r\n<loc>http://47.104.155.229:7788[field:typelink /]</loc>\r\n\r\n<changefreq>daily</changefreq>\r\n\r\n<priority>0.8</priority>\r\n\r\n</url>\r\n\r\n",372,565);
$z[1][4]=array();
$z[1][4]['row']="23";
$z[1][4]['type']="top";
$z[2]=Array("arclist","\r\n\r\n<url>\r\n\r\n<loc>http://47.104.155.229:7788[field:arcurl/]</loc>\r\n\r\n<lastmod>[field:pubdate function=strftime('%Y-%m-%d',@me)/]\r\n\r\n</lastmod>\r\n\r\n<changefreq>monthly</changefreq>\r\n\r\n</url>\r\n\r\n",569,815);
$z[2][4]=array();
$z[2][4]['row']="2000";
$z[2][4]['orderby']="pubdate";

?>